name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build Backend Docker Image
        run: docker build ./backend

      - name: Build Frontend Docker Image
        run: docker build ./frontend