name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Backend Docker Image
        run: docker build -t recipe-backend ./backend

      - name: Build Frontend Docker Image
        run: docker build -t recipe-frontend ./frontend

      - name: Run Backend Container (test)
        run: docker run -d -p 5000:5000 recipe-backend

      - name: Run Frontend Container (test)
        run: docker run -d -p 3000:3000 recipe-frontend